import { Setting, categories } from '@/lib/types';

export const defaultSettings: Setting[] = [
    {
        name: 'Clip name formatting',
        description:
            'The format of the clip name. You can use the following variables: %Y, %y, %m, %d, %H, %I, %M, %S, %f, %p',
        tooltip:
            '%Y: Full year (2025), %y: Short year (25), %m: Month (01-12), %d: Day of the month (01-31), %H: Hour (00-23), %I: Hour (01-12), %M: Minute (00-59), %S: Second (00-59), %f: Milliseconds (237), %p: AM/PM',
        type: 'string',
        defaultValue: '%Y-%m-%d_%H:%M:%S',
        storageKey: 'clip_name_formatting',
        category: categories.general,
    },
    {
        name: 'Clip length',
        description: 'The length of the clip in seconds.',
        type: 'select',
        options: [30, 60, 120, 180, 240, 300, 600],
        defaultValue: 120,
        storageKey: 'clip_length_s',
        category: categories.general,
    },
    {
        name: 'Clip resolution',
        description: 'The resolution of the clip. Higher resolution means larger file size.',
        type: 'select',
        options: ['1280x720', '1920x1080', '2560x1440', '3840x2160'],
        defaultValue: '1920x1080',
        storageKey: 'clip_resolution',
        category: categories.general,
    },
    {
        name: 'Clip FPS',
        description: 'The FPS of the clip. Higher FPS means smoother video.',
        type: 'select',
        options: [24, 30, 60, 120],
        defaultValue: 30,
        storageKey: 'clip_fps',
        category: categories.general,
    },
    {
        name: 'Video codec',
        description: 'The codec to use for the video.',
        type: 'select',
        options: ['h264', 'hevc', 'vp9'],
        defaultValue: 'h264',
        storageKey: 'video_codec',
        category: categories.general,
    },
    {
        name: 'Audio codec',
        description: 'The codec to use for the audio.',
        type: 'select',
        options: ['aac', 'opus', 'mp3'],
        defaultValue: 'aac',
        storageKey: 'audio_codec',
        category: categories.general,
    },
    {
        name: 'Audio bitrate',
        description: 'The bitrate of the audio in kbps.',
        type: 'select',
        options: [64, 128, 192, 256],
        defaultValue: 128,
        storageKey: 'audio_bitrate',
        category: categories.general,
    },
    {
        name: 'Include audio',
        description: 'Whether to include audio in the clip.',
        type: 'boolean',
        defaultValue: true,
        storageKey: 'include_audio',
        category: categories.general,
    },
    {
        name: 'Save location',
        description: 'The location to save the clips, starting from your home directory.',
        tooltip: 'e.g. Videos/wayclip will be parsed as /home/user/Videos/wayclip',
        type: 'string',
        defaultValue: 'Videos/wayclip',
        storageKey: 'save_path_from_home_string',
        category: categories.general,
    },
    {
        name: 'Save shortcut',
        description: 'The shortcut to save the clip.',
        tooltip: 'You can use the following modifiers: Ctrl, Alt, Shift, Meta (Windows key)',
        type: 'string',
        defaultValue: 'Alt+C',
        storageKey: 'save_shortcut',
        category: categories.shortcuts,
    },
    {
        name: 'Open GUI shortcut',
        description: 'The shortcut to open the GUI.',
        tooltip: 'You can use the following modifiers: Ctrl, Alt, Shift, Meta (Windows key)',
        type: 'string',
        defaultValue: 'Ctrl+Alt+C',
        storageKey: 'open_gui_shortcut',
        category: categories.shortcuts,
    },
    {
        name: 'Toggle notifications',
        description: 'Whether to show notifications inside the app.',
        type: 'boolean',
        defaultValue: true,
        storageKey: 'toggle_notifications',
        category: categories.ui,
    },
];
