[package]
name = "wayclip_trigger"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell = "1.21.3"
rodio = "0.21.1"
tokio = { version = "1", features = ["full"] }
wayclip_shared = { path = "../wayclip_shared" }
