name: Wayclip API Docker Image
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    if: "contains(github.event.head_commit.message, '[DOCKER]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install All System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            libssl-dev \
            patchelf \
            
            libgtk-3-dev \
            libwebkitgtk-6.0-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            
            libgstreamer1.0-dev \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly \
            gstreamer1.0-libav \
            libpipewire-0.3-dev \
            libasound2-dev \
            libavcodec-dev \
            libavformat-dev \
            libavutil-dev \
            libswscale-dev \
            
            libwayland-dev \
            libx11-dev \
            libxcb1-dev \
            libxkbcommon-dev \
            libxrandr-dev \
            libdbus-1-dev \
            
            libpq-dev \
            libssh2-1-dev

      - name: Install sqlx-cli
        run: cargo install sqlx-cli

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Verify SQLx offline data is up-to-date
        run: |
          cargo install sqlx-cli --force
          cargo sqlx prepare --workspace --check -- --workspace --exclude wayclip_gui

      - name: Run API tests
        run: cargo test --verbose -p wayclip_api

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: konyogonydev/wayclip-api:latest
