name: Wayclip Docs Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    if: "contains(github.event.head_commit.message, '[DOCS]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./wayclip_docs
          file: ./wayclip_docs/Dockerfile
          push: true
          tags: konyogonydev/wayclip-docs:latest
          platforms: linux/amd64,linux/arm64
